export const patterns = [
    
    [
    "buZigzagH",
    "buZigzagH",
    "buZigzagH",
    "buZigzagH",
    "buZigzagH",
    
    "buZigzagH",
    "buZigzagH",
    "buZigzagH",
    "buZigzagH",
    "buZigzagH",

    "buZigzagH",
    "buZigzagH",
    "buZigzagH",
    "buZigzagH",
    "buZigzagH",

    "buZigzagH",
    "buZigzagH",
    "buZigzagH",
    "buZigzagH",
    "buZigzagH",

    "buZigzagH",
    "buZigzagH",
    "buZigzagH",
    "buZigzagH",
    "buZigzagH",
    ],
    [
    "ldSquare",
    "ldSquare",
    "ldSquare",
    "ldSquare",
    "ldSquare",

    "ldSquare",
    "ldSquare",
    "ldSquare",
    "ldSquare",
    "ldSquare",
    
    "ldSquare",
    "ldSquare",
    "ldSquare",
    "ldSquare",
    "ldSquare",
    
    "ldSquare",
    "ldSquare",
    "ldSquare",
    "ldSquare",
    "ldSquare",
    
    "ldSquare",
    "ldSquare",
    "ldSquare",
    "ldSquare",
    "ldSquare",
    ],
    [
    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",
    
    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",

    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",

    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",

    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",
    "lCutDiamond",
    ],
    [
    "lDiagonal",
    "lDiagonal",
    "lDiagonal",
    "lDiagonal",
    "lDiagonal",
    
    "lCornerStl",
    "lCornerRtr",
    "lDiagonal",
    "lCornerRtl",
    "lCornerStr",
    
    "lCornerRbl",
    "Eye",
    "lCutDiamond",
    "Eye",
    "lCornerRbr",
    
    "lDiagonal",
    "lCornerRbl",
    "DiamondsV",
    "lCornerRbr",
    "lDiagonal",
    
    "lDiagonal",
    "lDiagonal",
    "lDiagonal",
    "lDiagonal",
    "lDiagonal",
    ],
    [
    "Plaster",
    "Plaster",
    "Plaster",
    "Plaster",
    "Plaster",
    
    "Plaster",
    "Plaster",
    "Plaster",
    "Plaster",
    "Plaster",

    "Plaster",
    "Plaster",
    "Plaster",
    "Plaster",
    "Plaster",

    "Plaster",
    "Plaster",
    "Plaster",
    "Plaster",
    "Plaster",

    "Plaster",
    "Plaster",
    "Plaster",
    "Plaster",
    "Plaster",
    ],
    [
    "Angle",
    "Angle",
    "Angle",
    "Angle",
    "Angle",
    
    "Angle",
    "Angle",
    "Angle",
    "Angle",
    "Angle",

    "Angle",
    "Angle",
    "Angle",
    "Angle",
    "Angle",

    "Angle",
    "Angle",
    "Angle",
    "Angle",
    "Angle",

    "Angle",
    "Angle",
    "Angle",
    "Angle",
    "Angle",
    ],
    [
    "SquareCorners",
    "SquareCorners",
    "SquareCorners",
    "SquareCorners",
    "SquareCorners",
    
    "SquareCorners",
    "SquareCorners",
    "SquareCorners",
    "SquareCorners",
    "SquareCorners",

    "SquareCorners",
    "SquareCorners",
    "SquareCorners",
    "SquareCorners",
    "SquareCorners",

    "SquareCorners",
    "SquareCorners",
    "SquareCorners",
    "SquareCorners",
    "SquareCorners",

    "SquareCorners",
    "SquareCorners",
    "SquareCorners",
    "SquareCorners",
    "SquareCorners",
    ],
    [
    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",
    
    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",

    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",

    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",

    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",
    "bdDiagonal",
    ],
];